project: terminal
generated_at: 2026-02-04 22:12 UTC
environment:
  python_version: '>=3.13'
  venv_path: .venv
  package_manager: npm
services:
  backend_port: 8000
  frontend_port: 3002
  infrastructure:
    neo4j: 7687
    postgres: 5432
    redis: 6379
pages:
- / (app)
tables:
- agent_sessions
- artifacts
- backup_schedules
- backups
- code_health_lists
- design_rules
- design_standards
- events
- explorer_entries
- explorer_relationships
- explorer_sub_elements
- ideas
- migration_backup
- mockups
- model_performance_logs
- model_performance_metrics
- notifications
- project_agent_config
- projects
- qa_issues
- quality_check_results
- refactor_sessions
- scan_history
- scan_states
- sitemap_entries
- subtask_citations
- subtask_dependencies
- subtask_summaries
- task_dependencies
- task_labels
- task_spirit
- task_subtask_steps
- task_subtasks
- tasks
- terminal_panes
- terminal_project_settings
- terminal_sessions
- user_prompts
folders:
  (root): 19 files - tests
  .claude: 6 files - tests
  .dev-tools: 9 files - tests
  .summitflow: 1 files
  frontend: 119 files - api, components, tests
  scripts: 14 files
  spec: 5 files - tests
  tasks: 38 files
  terminal: 50 files - api, services
