project: terminal
generated_at: 2026-01-29 02:12 UTC
pages:
- / (app)
tables:
- agent_sessions
- artifacts
- backup_schedules
- backups
- code_health_lists
- design_rules
- design_standards
- events
- explorer_entries
- explorer_relationships
- explorer_sub_elements
- ideas
- migration_backup
- mockups
- notifications
- project_agent_config
- projects
- qa_issues
- quality_check_results
- refactor_sessions
- scan_history
- scan_states
- sitemap_entries
- subtask_citations
- subtask_dependencies
- subtask_summaries
- task_dependencies
- task_labels
- task_spirit
- task_subtask_steps
- task_subtasks
- tasks
- terminal_panes
- terminal_project_settings
- terminal_sessions
- user_prompts
folders:
  (root): 18 files - tests
  .claude: 6 files - tests
  .dev-tools: 11 files - tests
  frontend: 93 files - api, components, tests
  scripts: 14 files
  spec: 5 files - tests
  tasks: 38 files
  terminal: 41 files - api, services
