project: terminal
total_files: 202
folders:
  (root): 17 files - config, docs, tests - (0, claude, gitignore, json, md)
  .claude: 6 files - docs, tests - (md)
  frontend: 89 files - components, config, docs, storage, tests - (css, gitignore,
    json, md, mjs)
  scripts: 9 files - (sh)
  spec: 5 files - docs, tests - (json, md)
  tasks: 35 files - (json)
  terminal: 41 files - api, config, models, services, storage - (py)
